# Generated by Django 4.2.3 on 2023-08-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update', models.BooleanField(default=False)),
                ('version_app', models.CharField(max_length=255, verbose_name='Версия приложения')),
                ('short_text', models.CharField(max_length=255, verbose_name='Заголовок описания')),
                ('text_app', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cmndr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cmdr', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('code_active', models.CharField(max_length=255, verbose_name='Уникальный код')),
                ('active', models.BooleanField(default=False)),
                ('monitor', models.IntegerField(verbose_name='ID монитора')),
                ('screen_size', models.CharField(max_length=255, verbose_name='Размеры экрана')),
                ('keyboard_layout', models.TextField(verbose_name='Раскладка клавиатуры')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.description')),
                ('global_activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.globalactive')),
            ],
        ),
    ]
