# Generated by Django 4.2.3 on 2023-08-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmndr',
            name='description',
        ),
    ]
