# Generated by Django 4.2.3 on 2023-08-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_cmndr_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmndr',
            name='code_active',
            field=models.CharField(max_length=255, unique=True, verbose_name='Уникальный код'),
        ),
    ]
