# Generated by Django 4.2.3 on 2023-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_cmndr_code_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalactive',
            name='check_stat',
            field=models.BooleanField(default=True),
        ),
    ]
