# Generated by Django 4.2.3 on 2023-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_description_short_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmndr',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='telegram_id'),
        ),
    ]
